rhel7_job:
  tags:
    - rhel7
  variables:
    WORKON_HOME: /localhome/gitlab-runner/pipenv
  before_script:
    - pipenv install --dev
  script:
    - pipenv run tests
    - pipenv run mypy
    - pipenv run docs
    - dls-python3 setup.py bdist_wheel
