include:
  - project: 'controls/reports/ci_templates'
    ref: 0-11
    file: 'all_templates.yml'
  - project: 'controls/python3/versiongit'
    file: '.mypy.yml'

stages:
  - run tests
  - static code checks
  - static type check
  - publish coverage
  - publish docs

# Run unit tests, make coverage report and build docs
Unit tests and coverage:
  stage: run tests
  extends:
    - .template_py3_pytest_and_coverage
  variables:
    COVERAGE_ARGS: --cov=versiongit --cov-report term-missing --cov-fail-under 90
    TEST_DIR: test
  artifacts:
    paths:
    # Pass on virtualenv, coverage and built docs to following stages
    - venv
    - .coverage
    - docs/_build/html/
    expire_in: 10 min

# Run our custom flake8 and black checks
Static code checks:
  tags:
    - rhel7
  stage: static code checks
  variables:
    FLAKE8_MODULES: versiongit test
    BLACK_MODULES: versiongit test
  extends:
    - .flake8_and_black

# Run our custom mypy check
Static type checks:
  tags:
    - rhel7
  stage: static type check
  variables:
    MYPY_MODULES: versiongit test
  extends:
    - .mypy


# Publish coverage html report to common location
Publish coverage:
  stage: publish coverage
  extends:
    .template_publish_coverage

# Install the docs for each push to master to "latest"
Install docs for latest master:
  stage: publish docs
  tags:
    - rhel7
  only:
    - master
  script:
    - pipenv run sphinx-build -b html -E -q docs docs/_build/html
    - mkdir -p ${DOCS_PUBLISH_ROOT}
    - cp -rf docs/_build/html ${DOCS_PUBLISH_ROOT}/latest

# Install the docs for each tag to their own directory
Install docs for tags:
  stage: publish docs
  tags:
    - rhel7
  only:
    - tags
  script:
  - pipenv run sphinx-build -b html -E -q docs docs/_build/html
  - mkdir -p ${DOCS_PUBLISH_ROOT}
  - cp -rf docs/_build/html ${DOCS_PUBLISH_ROOT}/${CI_COMMIT_TAG}
