env:
  global:
    # This sets SOURCE_DATE_EPOCH to the date of the last commit for reproducible builds
    # See here for more info : https://reproducible-builds.org/
    - SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - env
  - pip install coveralls
  # skip lock as we can't get a consistent lock on 2.7 and 3.x
  - pipenv install -v --dev --skip-lock
  - ls -al ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages
  - ls -al ${VIRTUAL_ENV}/bin
  - python setup.py bdist_wheel

script:
  - pipenv run tests
  - pipenv run docs

after_script:
  - coveralls

deploy:
  provider: pypi
  edge: true
  user: "__token__"
  password:
    secure: "nAzi0cSLbPEp+MPo+qRMsvyssHx6vsg75VRbxWb0wIypZ9GC2c5jq8YSMIm0IoB7bkQUemdGljwj/gTh2pPV3viNvMs3r+v+3FoQ5n9CAXeGsTXWvxzvj+GrVKtG35kUlibEE1l+mnE0bgZmLYefL7+Y3pbA3EVA7WWMsF/26+OxeomSjwiEQDZ9Ws6sWdYG/ki4Snn04RkL8kwr5k1EjSSAdppeENjGO8a5wWLOGhibtTRhIoH2sm2M5wGuS2V9NHwSJA6sl/J18lVB87ag+tmmYP1OPypwQmN0v0bJE/AgSdRabGnIqtoe5uGicvs0E6lVGCDNsTImXtzq0ecx5n5JyHUiNIC6rJy/6/I3YmrQUQg/4x/04CrGvqOt54fI0gZnMbaGrL3hcGRoDP7hGnW5FX0NI3SURCQBVkIHctIqxK80kw57BEae/ZCccWbojFXj85UdHwAcShCxvYj4Jrrqb/nNL6ixFdbxTLgrRgN25XvWA4Le/J8if/7ex5OZwi/WunfByBtz6st5TIGBJtL4K4VvsrGGxHhecR0xcf1OTdrhlK4BytVnAIs+8GqmIMqUvdAzkWN6Dj04S00OBLPx+tzyivjhBkiDXKemOdtCzQz2Dt27VZWDG2J3NgrTmOsCBoQAT9Q662RBLt2rw5ZqI+LwBr2uZXxMMZqthTs="
  distributions: "sdist bdist_wheel"
  # Use the same version of wheel as inside DLS
  wheel_version: "0.33.1"
  skip_existing: true
  on:
    tags: true
